### ISSUE TITLE
Better title for the draft

### ISSUE THREAD

**Issue by hannestschofenig** [ietf-wg-wimse/draft-ietf-wimse-workload-identity-practices#6]
At our recent conference call we talked about better aligning the content of the draft with the title of the document. The body of the document talks about the use of JWTs with OAuth 2.0 in a container environment utilizing token change. The title is, however, so generic that we could also describe other practices. Among the authors we had not planned to extend the scope (of course, to be confirmed by the group). 
 
I asked ChatGPT for a few suggestions regarding the title and here are the options:

- "Best Current Practice for Secure Workload Identity Management"
- "Best Current Practice in OAuth-Based Workload Identity"
- "Best Current Practice for JWT-Based Workload Identity"
- "Best Current Practice for Workload Identity in Container Orchestration"
- "Best Current Practice for Workload Identity Using OAuth 2.0 and JWT"
- 

I like the last one best. What do others think?

**Comment by b3n3d17** [comment]
I believe the last 2 fit best:
"Best Current Practice for Workload Identity in Container Orchestration"
"Best Current Practice for Workload Identity Using OAuth 2.0 and JWT"

or:

"Best Current Practice for OAuth 2.0 Client Authentication in [k8s|Container Orchestration] utilising JWT"

**Comment by edoardogiordano** [comment]
I also support the last one. 
It well explains the scope and allows future work on similar topics.

**Comment by arndt-s** [comment]
Some ideas based on above:
- Something "Current Practices"
    - e.g. "Current Workload Identity Practices"
- Something "Provisioning and Federation"
    - e.g. "Workload Identity Provisioning and Federation"
- Something "Provisioning and Assertions"
    - e.g. "Provisioning and OAuth Assertion in Workload Environments"

**Comment by arndt-s** [comment]
Resolved by direct commits to main by Justin. Title is "Workload Identity Practices".
